name: Auto approve
on: pull_request_target

jobs:
  build:
    if: github.actor == 'OliverKeyesKrysakowski' || github.actor == 'swapnilroy77' || github.actor == 'LucaM-Z' || github.actor == 'lowziwei' || github.actor == 'TheAnonymous-stack' || github.actor == 'akcljt' || github.actor == 'cherienessa'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v4
